# Generated by Django 4.0.2 on 2022-02-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_alter_area_options_alter_deposit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'managed': False, 'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'managed': False, 'verbose_name': 'Месторождение', 'verbose_name_plural': 'Месторождения'},
        ),
        migrations.AlterModelOptions(
            name='enterprise',
            options={'managed': False, 'verbose_name': 'Недропользователь', 'verbose_name_plural': 'Недропользователи'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'managed': False, 'verbose_name': 'Лицензия', 'verbose_name_plural': 'Лицензии'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'managed': False, 'verbose_name': 'Населенный пункт', 'verbose_name_plural': 'Населенные пункты'},
        ),
        migrations.AlterModelOptions(
            name='municipalitytype',
            options={'managed': False, 'verbose_name': 'Тип населенных пунктов', 'verbose_name_plural': 'Типы населенных пунктов'},
        ),
    ]
