# Generated by Django 4.0.2 on 2022-02-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_alter_area_options_alter_deposit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsoilUsers',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100, verbose_name='Наименование')),
                ('tin', models.CharField(db_column='TIN', max_length=12, unique=True, verbose_name='ИНН')),
                ('iec', models.CharField(blank=True, db_column='IEC', max_length=9, null=True, verbose_name='КПП')),
                ('psrn_psrnsp', models.CharField(db_column='PSRN/PSRNSP', max_length=15, unique=True, verbose_name='ОГРН')),
                ('date_of_registration', models.DateField(db_column='DateOfRegistration', verbose_name='Дата регистрации')),
                ('director', models.CharField(db_column='Director', max_length=100, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Недропользователь',
                'verbose_name_plural': 'Недропользователи',
                'db_table': 'subsoilusers',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Enterprise',
        ),
    ]
