# Generated by Django 4.0.2 on 2022-02-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(db_column='Message', verbose_name='Текст сообщения')),
                ('date', models.DateTimeField(db_column='Date', verbose_name='Дата сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_column='Login', max_length=100, verbose_name='Логин')),
                ('first_name', models.CharField(db_column='FirstName', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(db_column='LastName', max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, db_column='Patronymic', max_length=100, null=True, verbose_name='Отчество')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('phone', models.CharField(db_column='Phone', max_length=20, verbose_name='Телефон')),
                ('password', models.CharField(db_column='Password', max_length=100, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
