# Generated by Django 4.0.2 on 2022-02-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('development', models.CharField(blank=True, db_column='Development', max_length=30, null=True)),
                ('a_b_c1_kg', models.FloatField(blank=True, db_column='A+B+C1, kg', null=True)),
                ('c2_kg', models.FloatField(blank=True, db_column='C2, kg', null=True)),
                ('off_balance_kg', models.FloatField(blank=True, db_column='Off-balance, kg', null=True)),
            ],
            options={
                'db_table': 'deposit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('tin', models.CharField(db_column='TIN', max_length=12, unique=True)),
                ('iec', models.CharField(blank=True, db_column='IEC', max_length=9, null=True)),
                ('psrn_psrnsp', models.CharField(db_column='PSRN/PSRNSP', max_length=15, unique=True)),
                ('dateofregistration', models.DateField(db_column='DateOfRegistration')),
                ('director', models.CharField(db_column='Director', max_length=100)),
            ],
            options={
                'db_table': 'enterprise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=15)),
                ('startdate', models.DateField(db_column='StartDate')),
                ('enddate', models.DateField(db_column='EndDate')),
                ('cancelled', models.BooleanField(db_column='Cancelled')),
                ('destination', models.CharField(db_column='Destination', max_length=255)),
                ('diversion', models.CharField(db_column='Diversion', max_length=30)),
            ],
            options={
                'db_table': 'license',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('message', models.TextField(db_column='Message')),
                ('date', models.DateTimeField(db_column='Date')),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('direction', models.CharField(db_column='Direction', max_length=20)),
                ('distance', models.FloatField(db_column='Distance')),
            ],
            options={
                'db_table': 'municipality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MunicipalityType',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'municipalitytype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('login', models.CharField(db_column='Login', max_length=100)),
                ('firstname', models.CharField(db_column='FirstName', max_length=100)),
                ('lastname', models.CharField(db_column='LastName', max_length=100)),
                ('patronymic', models.CharField(blank=True, db_column='Patronymic', max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(db_column='Phone', max_length=20)),
                ('password', models.CharField(db_column='Password', max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'db_table': 'area',
                'managed': True,
            },
        ),
    ]
